In [6]:
import numpy as np
L=[2,3,4,56,7]
type(L)
arr=np.array(L)
# print(arr)
type(arr)
am=(np.arange(25))
print(am.shape)
np.linspace(2,3,10)
akm=am.reshape(5,5)
print(akm)


(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [13]:
import numpy as np

# Define the arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[11, 12, 13], [14, 15, 16]])
print(np.min(array1))
print(np.max(array1))

# Concatenate the arrays along axis 0 (rows)
concatenated_array = np.concatenate((array1, array2), axis=0)

print("Concatenated Array:")
print(concatenated_array)


#ar1=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#arr2 = np.array([[11, 12], [14, 15, 16]])
#comn=np.concatenated((ar1,arr2))
#print(comn)

1
9
Concatenated Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]]


In [69]:
# Create an array
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

# Use boolean indexing to get numbers greater than 5 and divisible by 2
result = numbers[(numbers > 5)]
print(result)
result1 = numbers[(numbers > 5) & (numbers % 2 == 0)] 
print(numbers[(numbers > 5) & (numbers % 2 == 0)])

num=[6,5,4,3,2,1]
print(sorted(num))


[ 6  7  8  9 10]
[ 6  8 10]
[1, 2, 3, 4, 5, 6]


In [3]:
import numpy as np

# Creating matrices A and B
A = np.array([[1, 2, 3],
              [3, 4, 4]])

B = np.array([[5, 6, 1],
              [7, 8, 0]])

# Addition of matrices A and B
addition = A + B

# Subtraction of matrices A and B
subtraction = A - B

# Element-wise multiplication of matrices A and B
elementwise_multiplication = A * B

# Scalar multiplication of matrix A by a scalar value
scalar = 2
scalar_multiplication = scalar * A

# Transpose of matrix A
transpose_A = np.transpose(A)

# Inverse of matrix A (if invertible)
try:
    inverse_A = np.linalg.inv(A)
except np.linalg.LinAlgError:
    inverse_A = "Matrix A is not invertible"

# Printing the results
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nElement-wise multiplication:\n", elementwise_multiplication)
print("\nScalar multiplication:\n", scalar_multiplication)
print("\nTranspose of matrix A:\n", transpose_A)
print("\nInverse of matrix A:\n", inverse_A)


Matrix A:
 [[1 2 3]
 [3 4 4]]

Matrix B:
 [[5 6 1]
 [7 8 0]]

Addition:
 [[ 6  8  4]
 [10 12  4]]

Subtraction:
 [[-4 -4  2]
 [-4 -4  4]]

Element-wise multiplication:
 [[ 5 12  3]
 [21 32  0]]

Scalar multiplication:
 [[2 4 6]
 [6 8 8]]

Transpose of matrix A:
 [[1 3]
 [2 4]
 [3 4]]

Inverse of matrix A:
 Matrix A is not invertible


In [12]:
for i in range(1,10,2):
    print(i)
type(i)

1
3
5
7
9


int

In [8]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
for i in range(1,10,9):
    print(i/2.5)

0.4


In [10]:
import numpy as np
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])